version: '3'
services:
  backend-server:
    platform: linux/amd64
    container_name: backend-server
    restart: always
    volumes:
      - ./nft-backend:/app
    ports:
      - "8075:8075"
    links:
      - mongo-db
    depends_on:
      - mongo-db
    env_file: 
      - ./nft-backend/.env
    networks:
      - backend
      - frontend
  mongo-db:
    container_name: mongo-db
    image: mongo
    # environment:
      # - MONGO_INITDB_DATABASE=
      # - MONGO_INITDB_ROOT_USERNAME=
      # - MONGODB_ROOT_PASSWORD=
    volumes:
      - ./mongo-db-volume:/data/db
    ports:
      - '27017-27019:27017-27019'
    networks:
      - backend
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
networks:
  backend:
    driver: bridge
    name: backend
  frontend:
    driver: bridge
    name: fronten
volumes:
  mongo-db:
    driver: local
    name: mongo-db-volume